#!/bin/bash

# NOIZYLAB Email Setup Wizard
# This script helps you configure your email system step by step

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🚀 NOIZYLAB EMAIL SETUP WIZARD - Let's Get Started!    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if .env already exists
if [ -f "config/.env" ]; then
    echo "⚠️  config/.env already exists!"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Your existing configuration is safe."
        exit 0
    fi
fi

echo "📧 Let's configure your email system!"
echo ""
echo "Choose your email provider:"
echo "  1) Gmail"
echo "  2) Outlook/Hotmail"
echo "  3) Yahoo Mail"
echo "  4) Custom SMTP Server"
echo ""
read -p "Enter your choice (1-4): " provider_choice

# Set defaults based on provider
case $provider_choice in
    1)
        SMTP_HOST="smtp.gmail.com"
        SMTP_PORT="587"
        SMTP_SECURE="false"
        echo ""
        echo "📌 Gmail Configuration Selected"
        echo "NOTE: You'll need to use an 'App Password' for Gmail."
        echo "Create one at: https://myaccount.google.com/apppasswords"
        ;;
    2)
        SMTP_HOST="smtp-mail.outlook.com"
        SMTP_PORT="587"
        SMTP_SECURE="false"
        echo ""
        echo "📌 Outlook Configuration Selected"
        ;;
    3)
        SMTP_HOST="smtp.mail.yahoo.com"
        SMTP_PORT="587"
        SMTP_SECURE="false"
        echo ""
        echo "📌 Yahoo Mail Configuration Selected"
        echo "NOTE: You may need to enable 'Less secure app access' in Yahoo settings."
        ;;
    4)
        echo ""
        read -p "Enter SMTP Host (e.g., smtp.example.com): " SMTP_HOST
        read -p "Enter SMTP Port (usually 587 or 465): " SMTP_PORT
        read -p "Use SSL/TLS? (true/false): " SMTP_SECURE
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

echo ""
echo "📝 Enter your email credentials:"
echo ""
read -p "Email address (from): " SMTP_USER

# Read password securely
echo -n "Email password (or app password): "
read -s SMTP_PASS
echo ""

echo ""
read -p "Server port for the agent (default 3000): " SERVER_PORT
SERVER_PORT=${SERVER_PORT:-3000}

# Create the .env file
cat > config/.env << EOF
# NOIZYLAB Email System Configuration
# Generated by setup wizard on $(date)

# SMTP Configuration
SMTP_HOST=$SMTP_HOST
SMTP_PORT=$SMTP_PORT
SMTP_SECURE=$SMTP_SECURE
SMTP_USER=$SMTP_USER
SMTP_PASS=$SMTP_PASS

# Server Configuration
SERVER_PORT=$SERVER_PORT
SERVER_HOST=0.0.0.0

# Logging
LOG_LEVEL=info
EOF

echo ""
echo "✅ Configuration saved to config/.env"
echo ""

# Offer to install dependencies
if [ ! -d "node_modules" ]; then
    read -p "Install dependencies now? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo ""
        echo "📦 Installing dependencies..."
        npm install
        echo "✅ Dependencies installed!"
    fi
fi

echo ""
echo "╔════════════════════════════════════════════════════════════╗"
echo "║               ✅ SETUP COMPLETE!                          ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 Next Steps:"
echo ""
echo "1. Test your configuration:"
echo "   bash test_email.sh"
echo ""
echo "2. Start the agent:"
echo "   npm start"
echo ""
echo "3. Send your first email:"
echo "   curl -X POST http://localhost:$SERVER_PORT/agent/send-email \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"to\":\"recipient@example.com\",\"subject\":\"Test\",\"text\":\"Hello!\"}'"
echo ""
echo "📚 Documentation: README.md"
echo ""
echo "🚀 Ready to send emails at WARP SPEED!"
